#!/bin/bash
echo "@shmadul's Serial Terminal"
echo "Much More Stable than ATS or CoolTerm"
local='ls /dev/tty.usb*'
port='115200'
tempfile=$(mktemp /tmp/serial.terminal)
echo "#!/bin/bash
screen ${local:3} $port" > $tempfile
chmod +x $tempfile
$tempfile
rm "$tempfile"