#!/bin/bash
echo "@shmadul's Serial Terminal"
echo "Much More Reliable than ATS or CoolTerm"
local='ls /dev/tty.usb*'
port='115200'
cache=$(mktemp /tmp/serial.terminal)
echo "#!/bin/bash
screen ${local:3} $port" > $cache
chmod +x $cache
$cache
rm "$cache"